tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "iainbeeston/custom"
brew "aspell"
brew "bat"
brew "chruby"
brew "direnv"
brew "emacs"
brew "gettext"
brew "gh"
brew "git"
brew "hivemind"
brew "icdiff"
brew "jq"
brew "mas"
brew "node-build"
brew "nodenv"
brew "perl"
brew "postgresql"
brew "redis"
brew "ruby-install"
brew "scmpuff"
brew "svgo"
brew "the_silver_searcher"
brew "tree"
brew "vim"
brew "yarn"
brew "yq"
brew "zsh"
cask "authy"
cask "chromedriver"
cask "dash"
cask "docker"
cask "finicky"
cask "google-chrome"
cask "grandperspective"
cask "imagealpha"
cask "imageoptim"
cask "iterm2"
cask "java"
cask "karabiner-elements"
cask "launchcontrol"
cask "rectangle"
cask "slack"
cask "spotify"
cask "validator-sac"
cask "visual-studio-code"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Session", id: 1521432881
mas "Xcode", id: 497799835
